step1 import pantas

In [1]:
import pandas as pd

step 2 check the dataset filename

In [2]:
import os

data_path = "../data"

print(os.listdir(data_path))

['water_quality_original.csv']

In [3]:
file_path = "../data/water_quality_original.csv"

print(file_path)

../data/water_quality_original.csv

Step 4 — Check the file size

Don't load the dataset yet. First check its size:

In [4]:
import os

file_size_mb = os.path.getsize(file_path) / (1024 * 1024)

print(f"File size: {file_size_mb:.2f} MB")

File size: 304.74 MB

In [5]:
# Step 5 — Read only a small sample
sample_df = pd.read_csv(file_path, nrows=1000)

print("Rows loaded:", len(sample_df))
print("Columns:", sample_df.columns.tolist())

Rows loaded: 1000
Columns: ['Country', 'Area', 'Waterbody Type', 'Date', 'Ammonia (mg/l)', 'Biochemical Oxygen Demand (mg/l)', 'Dissolved Oxygen (mg/l)', 'Orthophosphate (mg/l)', 'pH (ph units)', 'Temperature (cel)', 'Nitrogen (mg/l)', 'Nitrate (mg/l)', 'CCME_Values', 'CCME_WQI']

In [6]:
sample_df.head()

,Country,Area,Waterbody Type,Date,Ammonia (mg/l),Biochemical Oxygen Demand (mg/l),Dissolved Oxygen (mg/l),Orthophosphate (mg/l),pH (ph units),Temperature (cel),Nitrogen (mg/l),Nitrate (mg/l),CCME_Values,CCME_WQI
0,Canada,SE649035-145565,River,12-01-1974,0.059248,1.30,8.1500,0.011917,8.07500,9.885,0.343917,11.73155,100.0,Excellent
1,Canada,SE649035-145565,River,12-01-1975,0.039821,1.38,7.8000,0.009417,7.73333,10.150,0.449083,11.82009,100.0,Excellent
2,Canada,SE649035-145565,River,12-01-1976,0.031341,2.23,7.8000,0.011000,7.46667,10.235,0.220750,14.87472,100.0,Excellent
3,Canada,SE649035-145565,River,12-01-1977,0.020501,1.61,8.1500,0.012333,7.78333,11.116,0.572250,15.89293,100.0,Excellent
4,Canada,SE649035-145565,River,12-01-1978,0.020023,1.64,4.3708,0.006182,7.10000,7.068,0.371091,15.22888,100.0,Excellent

In [7]:
# step 6 check data types

sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           1000 non-null   str
 1   Area                              1000 non-null   str
 2   Waterbody Type                    1000 non-null   str
 3   Date                              1000 non-null   str
 4   Ammonia (mg/l)                    1000 non-null   float64
 5   Biochemical Oxygen Demand (mg/l)  1000 non-null   float64
 6   Dissolved Oxygen (mg/l)           1000 non-null   float64
 7   Orthophosphate (mg/l)             1000 non-null   float64
 8   pH (ph units)                     1000 non-null   float64
 9   Temperature (cel)                 1000 non-null   float64
 10  Nitrogen (mg/l)                   1000 non-null   float64
 11  Nitrate (mg/l)                    1000 non-null   float64
 12  CCME_Values                       1000 non-null   float64
 13  CCME_WQI                          1000 non-null   str
dtypes: float64(9), str(5)
memory usage: 147.3 KB

In [8]:
# step 7 check missing values in the sample 

sample_df.isnull().sum()

Country                             0
Area                                0
Waterbody Type                      0
Date                                0
Ammonia (mg/l)                      0
Biochemical Oxygen Demand (mg/l)    0
Dissolved Oxygen (mg/l)             0
Orthophosphate (mg/l)               0
pH (ph units)                       0
Temperature (cel)                   0
Nitrogen (mg/l)                     0
Nitrate (mg/l)                      0
CCME_Values                         0
CCME_WQI                            0
dtype: int64

In [10]:
# Step 8 - Create a random 100k row sample

import numpy as np

sample_size = 100000
chunksize = 100000

# First count rows without loading the entire dataset
total_rows = 0

for chunk in pd.read_csv(file_path, chunksize=chunksize):
    total_rows += len(chunk)

print("Total rows:", total_rows)

Total rows: 2827977

In [12]:
# Step 9 - Randomly sample 100,000 rows

sample_size = 100000
chunksize = 100000

sampled_chunks = []

# Use a slightly larger fraction so we definitely get
# more than 100,000 rows
fraction = (sample_size + 2000) / total_rows

for chunk in pd.read_csv(file_path, chunksize=chunksize):
    
    n = min(
        len(chunk),
        int(len(chunk) * fraction) + 1
    )
    
    sampled_chunk = chunk.sample(
        n=n,
        random_state=42
    )
    
    sampled_chunks.append(sampled_chunk)

# Combine sampled rows
df_100k = pd.concat(
    sampled_chunks,
    ignore_index=True
)

# Randomly select exactly 100,000 rows
df_100k = df_100k.sample(
    n=sample_size,
    random_state=42
).reset_index(drop=True)

print("Final rows:", len(df_100k))
print("Final columns:", len(df_100k.columns))

Final rows: 100000
Final columns: 14

In [13]:
print(df_100k.shape)

(100000, 14)

In [14]:
# Step 10 - Save the 100k working dataset

output_path = "../processed_data/water_quality_100k.csv"

df_100k.to_csv(output_path, index=False)

print("Dataset saved successfully!")
print("Saved at:", output_path)

Dataset saved successfully!
Saved at: ../processed_data/water_quality_100k.csv

In [15]:
import os

print(os.path.exists(output_path))

True

In [16]:
# Step 11 - Load the saved 100k dataset

df = pd.read_csv(output_path)

print("Shape:", df.shape)

Shape: (100000, 14)

In [17]:
# Step 12 - Check missing values

missing = df.isnull().sum()

print(missing)

Country                             0
Area                                0
Waterbody Type                      0
Date                                0
Ammonia (mg/l)                      0
Biochemical Oxygen Demand (mg/l)    0
Dissolved Oxygen (mg/l)             0
Orthophosphate (mg/l)               0
pH (ph units)                       0
Temperature (cel)                   0
Nitrogen (mg/l)                     0
Nitrate (mg/l)                      0
CCME_Values                         0
CCME_WQI                            0
dtype: int64

In [18]:
# Step 13 - Check duplicate rows

duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 16

In [19]:
# Step 14 - Check categorical information

print("Countries:", df["Country"].nunique())
print("Waterbody Types:", df["Waterbody Type"].nunique())

print("\nCountry distribution:")
print(df["Country"].value_counts())

print("\nWaterbody Type distribution:")
print(df["Waterbody Type"].value_counts())

Countries: 5
Waterbody Types: 12

Country distribution:
Country
England    75271
USA        14616
Ireland     8328
China       1635
Canada       150
Name: count, dtype: int64

Waterbody Type distribution:
Waterbody Type
River           65566
Effluent        21266
Lake             5414
Estuarine        1732
Bay              1635
Sea Water        1183
Canal             990
Sewage            810
Marine            785
Drainage          360
Transitional      156
Coastal           103
Name: count, dtype: int64

In [20]:
# Step 15 - Check date range

dates = pd.to_datetime(
    df["Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

print("Earliest date:", dates.min())
print("Latest date:", dates.max())

print("Invalid dates:", dates.isnull().sum())

Earliest date: 1940-04-25 00:00:00
Latest date: 2023-10-23 00:00:00
Invalid dates: 0

In [21]:
# Step 16 - Statistical summary

df.describe()

,Ammonia (mg/l),Biochemical Oxygen Demand (mg/l),Dissolved Oxygen (mg/l),Orthophosphate (mg/l),pH (ph units),Temperature (cel),Nitrogen (mg/l),Nitrate (mg/l),CCME_Values
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,1.141159,4.832689,10.008087,0.708421,7.735240,11.819261,5.207477,4.792220,85.095029
std,5.491133,16.149127,1.855390,2.069572,0.493827,4.995563,6.222716,6.187033,17.612858
min,0.000000,0.000000,0.000000,-0.003000,0.000000,-1.000000,0.000000,0.000000,34.854271
25%,0.030000,1.600000,9.860000,0.040000,7.550000,8.900000,0.760000,1.160000,77.197434
50%,0.054000,2.700000,10.200000,0.105000,7.780000,11.460000,3.940000,4.500000,90.700402
75%,0.316158,2.800000,11.000000,0.226000,8.000000,14.220000,6.310000,4.950000,100.000000
max,197.000000,255.000000,20.000000,100.000000,24.600000,90.000000,46.000000,155.000000,100.000000